### ISSUE TITLE
carthage Build Failed

### ISSUE THREAD

**Issue by horaceho** [davedelong/DDMathParser#143] opened 2017-11-29 06:16 UTC
````
$ carthage update --platform iOS
*** Fetching DDMathParser
*** Checking out DDMathParser at "3.0.0"
*** xcodebuild output can be found in /var/folders/yl/16770s0173131t02j3t6km_c0000gn/T/carthage-xcodebuild.y6CRZW.log
*** Building scheme "MathParser" in DDMathParser.xcodeproj


Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/horace/Projects/iOS/Swift/Apps/Calculatox/Carthage/Checkouts/DDMathParser/DDMathParser.xcodeproj -scheme MathParser -configuration Release -derivedDataPath /Users/horace/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/DDMathParser/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/horace/Projects/iOS/Swift/Apps/Calculatox/Carthage/Checkouts/DDMathParser)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yl/16770s0173131t02j3t6km_c0000gn/T/carthage-xcodebuild.y6CRZW.log
````
In log:
````
/(project-path)/Carthage/Checkouts/DDMathParser/MathParser/RewriteRule+Defaults.swift:50:7: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
    ].flatMap { $0 }
~~~~~~^~~~~~~~~~~~~~
````

**Comment by davedelong** [comment] 2017-12-15 00:49
Dupe of #139, which should be fixed.

**Closed by davedelong** 2017-12-15 00:49 UTC
