### ISSUE TITLE
What branch shall I use? What is the current state of the project?

### ISSUE THREAD

**Issue by Motti-Shneor** [davedelong/DDMathParser#93] opened 2014-12-30 13:33 UTC
Hello Dave and everyone. I made DDMathParser (master) a submodule of one of my projects, and enjoy using it a lot.

However, I saw many important issues and bugs resolved onto branch 1.1, and I suspect for lack of time or resources the changes and fixes never reached master.

Can someone "recommend" the latest stable version of DDMatphParser?

**Comment by davedelong** [comment] 2015-08-25 21:26
Duplicate of #90

**Closed by davedelong** 2015-08-25 21:26 UTC
