### ISSUE TITLE
sin(π()) != 0

### ISSUE THREAD

**Issue by baryon** [davedelong/DDMathParser#148] opened 2018-02-09 14:51 UTC
the result of sin(π) is not zero. 
sin(π()) = 1.22464679914735e-16

**Comment by davedelong** [comment] 2018-02-12 22:01
Sadly, this is a duplicate of issue #99. There’s not much I can do about it without a whole new math library (see issue #111).

**Closed** 2018-02-12 22:02 UTC

**Comment by Roman-Kerimov** [comment] 2019-03-19 04:27
This can be fixed so:
```
extension Double {
    func isDivisible(by value: Double) -> Bool {
        let decimalNumberFormatter = NumberFormatter.init()
        decimalNumberFormatter.numberStyle = .decimal
        return decimalNumberFormatter.string(from: .init(value: self/value))?.contains(decimalNumberFormatter.decimalSeparator) == false
    }
}

func sin(_ value: Double) -> Double {
    return value.isDivisible(by: .pi) ? 0 : Foundation.sin(value)
}
    
static func cos(_ value: Double) -> Double {
    return (.pi/2+value).isDivisible(by: .pi) ? 0 : Foundation.cos(value)
}
    
static func tan(_ value: Double) -> Double {
    return value.isDivisible(by: .pi) ? 0 : (.pi/2+value).isDivisible(by: .pi) ? .infinity : Foundation.tan(value)
}
```
